### PR TITLE
fixes #5

### LINKED ISSUE #5: Broken evaluation on indexed object.
Ref.: https://github.com/FlowCommunications/JSONPath/issues/21

Incorrect behavior caused by https://github.com/FlowCommunications/JSONPath/commit/5de3d83e60983e470222b53f9800355a61caf4ba

```json
{
           "store":{
              "books":{
                "4": {
                    "category":"reference",
                    "author":"Nigel Rees",
                    "title":"Sayings of the Century",
                    "price":8.95
                 },
                 "3": {
                    "category":"fiction",
                    "author":"Evelyn Waugh",
                    "title":"Sword of Honour",
                    "price":12.99
                 },
                 "2": {
                    "category":"fiction",
                    "author":"Herman Melville",
                    "title":"Moby Dick",
                    "isbn":"0-553-21311-3",
                    "price":8.99
                 },
                 "1": {
                    "category":"fiction",
                    "author":"J. R. R. Tolkien",
                    "title":"The Lord of the Rings",
                    "isbn":"0-395-19395-8",
                    "price":22.99
                 }
              }
           }
        }
```

Path
`$..book[3]`

Expected

```json
[
  {
    "category":"fiction",
    "author":"Evelyn Waugh",
    "title":"Sword of Honour",
    "price":12.99
  }
]
```

Actually 
```json
[
   {
      "category":"fiction",
      "author":"J. R. R. Tolkien",
      "title":"The Lord of the Rings",
      "isbn":"0-395-19395-8",
      "price":22.99
   }
]
```

### PR DESCRIPTION
**Pull request by oleg-andreyev**
added negative check before doing slice

### CODE REVIEW

File: tests/JSONPathTest.php [hunk 1]
```diff
@@ -800,26 +807,65 @@ public function exampleDataWithSlashes(int $asArray = 1)
...
+                    "author":"J. R. R. Tolkien",
+                    "title":"The Lord of the Rings",
+                    "isbn":"0-395-19395-8",
+                    "price":22.99
+                 }
+              }
+           }
+        }';
+
+        return json_decode($json, true);
```
Comment (SoftCreatR) [inline tests/JSONPathTest.php:866]: Please use `$asArray === 1` instead of `true`.

**Review by SoftCreatR — CHANGES_REQUESTED** [review]
